services:
  app:
    build: .
    container_name: edurisk
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./apache.conf:/etc/apache2/conf-available/z-mvc.conf
    depends_on:
      - db
    command: >
      bash -c "a2enmod rewrite &&
               a2enconf z-mvc &&
               apache2-foreground"

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: EduRisk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - db

volumes:
  db_data:
